task_id: "fedhar"
data:
  root: ""
  dataset: pkummd
  split_type: "iid"
  min_size: 10
  data_amount: 0.05
  iid_fraction: 0.1
  user: False
  train_test_split: 0.9
  class_per_client: 1
  num_of_clients: 2
  alpha: 0.5
  weights: NULL
server:
  test_all: False
  clients_per_round: 5
  rounds: 300
  batch_size: 128
  aggregation_content: "parameters"
  save_model_path: "/root/FL-HAR/FSAR/experiments"
resource_heterogeneous:
  simulate: False
  pre_profile: False
  total_time: 0
  grouping_strategy: "greedy"
client:
  test_batch_size: 128
  local_epoch: 1
  track: False
  batch_size: 128
  optimizer:
    type: "SGD"
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001